// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNH.Infrastructure.Data;

namespace QLNH.Infrastructure.Migrations
{
    [DbContext(typeof(QLNHDbContext))]
    [Migration("20200228075321_FirstCommit")]
    partial class FirstCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QLNH.Infrastructure.Entities.BookTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int>("CustomerBookingId");

                    b.Property<DateTime>("TimeBooking");

                    b.Property<int>("TypeBooking");

                    b.HasKey("ID");

                    b.ToTable("BookTables");
                });

            modelBuilder.Entity("QLNH.Infrastructure.Entities.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvartarURL");

                    b.Property<int?>("EmployeeId");

                    b.Property<int>("EmployeeType");

                    b.Property<string>("FullName");

                    b.Property<string>("IdentityId");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("QLNH.Infrastructure.Entities.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("QLNH.Infrastructure.Entities.RestaurantInformation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresss");

                    b.Property<string>("LogoURL");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("TimeToStartWorking");

                    b.HasKey("ID");

                    b.ToTable("RestaurantInformations");
                });

            modelBuilder.Entity("QLNH.Infrastructure.Entities.Table", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId");

                    b.Property<int>("TableStatus");

                    b.HasKey("ID");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("QLNH.Infrastructure.Entities.Employee", b =>
                {
                    b.HasOne("QLNH.Infrastructure.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("EmployeeId");
                });
#pragma warning restore 612, 618
        }
    }
}
